export enum ActionTypes {
    REQUSET_NEWS_LIST = 'REQUSET_NEWS_LIST',
    REQUSET_NEWS_SUCCESS = 'REQUSET_NEWS_SUCCESS',
    REQUSET_NEWS_ERROR = 'REQUSET_NEWS_ERROR',
    INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT',
    POSTS_IF_NEEDED = 'POSTS_IF_NEEDED'
}
