export enum globalActionTypes {
    SELECT_GLOBALE_THEME = 'SELECT_GLOBALE_THEME',
    SELECT_SUBREDDIT = 'SELECT_SUBREDDIT',
    SELECT_SIDE_BAR_COLLAPSED = 'SELECT_SIDE_BAR_COLLAPSED',
    SELECT_OPEN_KEYS = 'SELECT_OPEN_KEYS'
}

export enum AuthActionTypes {
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_RESPONSE = 'LOGIN_RESPONSE',
    LOGOUT_REQUEST = 'LOGOUT_REQUEST',
    LOGOUT_RESPONSE = 'LOGOUT_RESPONSE'
}

export enum ResetStateAction {
    RESET_SUB_STATE = 'RESET_SUB_STATE'
}
