export enum COOKIE_KEYS {
    TOKEN = 'token',
    KEYS = '00d91e8e0cca2b76f515926a36db68f5'
}

// 与ActionType保持一致
export enum LOCALSTORAGE_KEYS {
    USERINFO = 'LOGIN_RESPONSE',
    NAV_OPEN_KEYS = 'SELECT_OPEN_KEYS',
    SIDE_BAR_THEME = 'SELECT_GLOBALE_THEME',
    SIDE_BAR_COLLAPSED = 'SELECT_SIDE_BAR_COLLAPSED',
    SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
}

export const LOGIN_CATEGORY = ['user', 'admin']
